### ISSUE TITLE
在wsl2中安装后，启动时报错，请问这个是什么原因？

### ISSUE THREAD

**Issue by boyliwensheng** [datawhalechina/vced#54]
报错日志如下：
ERROR  Flow@21255 Flow is aborted due to ['video_loader', 'image_encoder', 'text_encoder',           [11/20/22 21:17:04]       'indexer'] can not be started.
Traceback (most recent call last):
  File "/home/liwensheng/rustprojects/testdir/vced/code/service/app.py", line 76, in <module>
    with f:
  File "/home/liwensheng/.local/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1106, in __enter__
    return self.start()
  File "/home/liwensheng/.local/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1161, in start
    self._wait_until_all_ready()
  File "/home/liwensheng/.local/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1259, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart

**Comment by boyliwensheng** [comment]
[上边那个问题通过这篇帖子解决了(https://zhuanlan.zhihu.com/p/404162713)
，但是又报了另一个错，有大佬知道什么原因吗：]ARNI… indexer/rep-0@27 <jina.orchestrate.pods.Pod object at 0x7fa0173402e0> timeout after waiting for 600000ms, if your executor takes time to load, you may increase       [11/20/22 23:14:17]
       --timeout-ready
ERROR  Flow@27 Flow is aborted due to ['indexer'] can not be started.                                                                                                        [11/20/22 23:37:37]
Traceback (most recent call last):
  File "/home/liwensheng/rustprojects/testdir/vced/code/service/app.py", line 76, in <module>
    with f:
  File "/home/liwensheng/.local/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1106, in __enter__
    return self.start()
  File "/home/liwensheng/.local/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1161, in start
    self._wait_until_all_ready()
  File "/home/liwensheng/.local/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1259, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
